org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

maven_group = io.github.skydynamic
archives_base_name = FuckMojangCarpetAddition

mod.id = fmca
mod.name = FuckMojangCarpetAddition
mod.version = 1.0.4
mod.description = The purpose of this mod is deleted or fix some minecraft features(bugs)

dependencies.minecraft_version = 26.2
dependencies.minecraft_dependency = 26.2
dependencies.loader_version = 0.19.5
dependencies.carpet_core_version = 26.2+v260616
java_version = 25
